In [1]:
import os
import sys

project_root = os.path.abspath("..")

sys.path.append(project_root)

print("Project Root:", project_root)

Project Root: c:\Users\Acer\OneDrive\Desktop\Social_Media_Teen_Health_Project

In [2]:
import pandas as pd

from src.feature_engineering.create_features import *

from src.feature_engineering.encoding import *

from src.feature_engineering.dimensionality_reduction import *

In [3]:
df = pd.read_csv(
    "../data/cleaned/cleaned_dataset.csv"
)

In [4]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,-0.952494,male,1.696054,instagram,0.632818,1.618934,0.034229,0.830744,low,-1.164130,-1.248781,-1.618124,0.0
1,1.521874,female,-1.278422,tiktok,1.051987,1.618934,0.398145,-0.371162,high,0.911418,-1.599785,1.567557,0.0
2,0.532127,female,-1.575870,instagram,0.772541,-1.737118,1.611198,-1.744768,high,-1.164130,-0.546773,-1.264159,0.0
3,-0.457621,male,1.448181,tiktok,0.283510,-0.198928,0.848707,-0.371162,medium,-1.510054,0.506238,1.213593,0.0
4,-0.457621,female,0.109666,both,-1.113721,1.758770,-1.074848,0.659043,medium,-0.818205,-0.195769,-1.264159,0.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1169 non-null   float64
 1   gender                    1169 non-null   str
 2   daily_social_media_hours  1169 non-null   float64
 3   platform_usage            1169 non-null   str
 4   sleep_hours               1169 non-null   float64
 5   screen_time_before_sleep  1169 non-null   float64
 6   academic_performance      1169 non-null   float64
 7   physical_activity         1169 non-null   float64
 8   social_interaction_level  1169 non-null   str
 9   stress_level              1169 non-null   float64
 10  anxiety_level             1169 non-null   float64
 11  addiction_level           1169 non-null   float64
 12  depression_label          1169 non-null   float64
dtypes: float64(10), str(3)
memory usage: 136.8 KB

In [6]:
df = create_addiction_score(df)

In [7]:
df[['addiction_score']].head()

   addiction_score
0         2.745799
1        -2.069682
2         2.737473
3        -0.288083
4         0.192878

In [8]:
df = create_sleep_disruption(df)

In [9]:
df[['sleep_disruption']].head()

   sleep_disruption
0                 1
1                 1
2                 1
3                 1
4                 1

In [10]:
df = create_usage_category(df)

In [11]:
df[['usage_category']].head()

  usage_category
0            low
1            NaN
2            NaN
3            low
4            low

In [12]:
print(df.columns)

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label',
       'addiction_score', 'sleep_disruption', 'usage_category'],
      dtype='str')

In [13]:
df = one_hot_encoding(df)

Encoding Completed.

In [14]:
df.head()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,addiction_score,sleep_disruption,gender_male,platform_usage_instagram,platform_usage_tiktok,social_interaction_level_low,social_interaction_level_medium,usage_category_medium,usage_category_high
0,-0.952494,1.696054,0.632818,1.618934,0.034229,0.830744,-1.164130,-1.248781,-1.618124,0.0,2.745799,1,True,True,False,True,False,False,False
1,1.521874,-1.278422,1.051987,1.618934,0.398145,-0.371162,0.911418,-1.599785,1.567557,0.0,-2.069682,1,False,False,True,False,False,False,False
2,0.532127,-1.575870,0.772541,-1.737118,1.611198,-1.744768,-1.164130,-0.546773,-1.264159,0.0,2.737473,1,False,True,False,False,False,False,False
3,-0.457621,1.448181,0.283510,-0.198928,0.848707,-0.371162,-1.510054,0.506238,1.213593,0.0,-0.288083,1,True,False,True,False,True,False,False
4,-0.457621,0.109666,-1.113721,1.758770,-1.074848,0.659043,-0.818205,-0.195769,-1.264159,0.0,0.192878,1,False,False,False,False,True,False,False

In [15]:
print(df.columns)

Index(['age', 'daily_social_media_hours', 'sleep_hours',
       'screen_time_before_sleep', 'academic_performance', 'physical_activity',
       'stress_level', 'anxiety_level', 'addiction_level', 'depression_label',
       'addiction_score', 'sleep_disruption', 'gender_male',
       'platform_usage_instagram', 'platform_usage_tiktok',
       'social_interaction_level_low', 'social_interaction_level_medium',
       'usage_category_medium', 'usage_category_high'],
      dtype='str')

In [16]:
pca_output = apply_pca(
    df,
    components=5
)

In [17]:
print(pca_output.shape)

(1169, 5)

In [18]:
df.to_csv(
    "../data/processed/engineered_features.csv",
    index=False
)

print("Processed dataset saved.")

Processed dataset saved.

In [19]:
df.head()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,addiction_score,sleep_disruption,gender_male,platform_usage_instagram,platform_usage_tiktok,social_interaction_level_low,social_interaction_level_medium,usage_category_medium,usage_category_high
0,-0.952494,1.696054,0.632818,1.618934,0.034229,0.830744,-1.164130,-1.248781,-1.618124,0.0,2.745799,1,True,True,False,True,False,False,False
1,1.521874,-1.278422,1.051987,1.618934,0.398145,-0.371162,0.911418,-1.599785,1.567557,0.0,-2.069682,1,False,False,True,False,False,False,False
2,0.532127,-1.575870,0.772541,-1.737118,1.611198,-1.744768,-1.164130,-0.546773,-1.264159,0.0,2.737473,1,False,True,False,False,False,False,False
3,-0.457621,1.448181,0.283510,-0.198928,0.848707,-0.371162,-1.510054,0.506238,1.213593,0.0,-0.288083,1,True,False,True,False,True,False,False
4,-0.457621,0.109666,-1.113721,1.758770,-1.074848,0.659043,-0.818205,-0.195769,-1.264159,0.0,0.192878,1,False,False,False,False,True,False,False